name = input("Enter name of the non medical staff: ")
age = input("Enter age of the non medical staff: ")
gender = input("Enter gender of the non medical staff: ")
nonmedicalstaff_id = input("Enter ID of the non medical staff: ")
department = input("Enter department of the non medical staff: ")
phone_number = input("Enter phone number of the non medical staff: ")
email = input("Enter email of the non medical staff: ")
address = input("Enter address of the non medical staff: ")
joining_date = input("Enter joining date of the non medical staff: ")
salary = input("Enter salary of the non medical staff: ")

file = open("nonmedicalstaffDetails.txt", "w")
file.write(name)
file.write("\n")
file.write(age)
file.write("\n")
file.write(gender)
file.write("\n")
file.write(nonmedicalstaff_id)
file.write("\n")
file.write(department)
file.write("\n")
file.write(phone_number)
file.write("\n")
file.write(email)
file.write("\n")
file.write(address)
file.write("\n")
file.write(joining_date)
file.write("\n")
file.write(salary)
file.write("\n")
file.close()
