medid = input("Enter med id: ")
nameofmed = input("Enter Name of Medicine: ")
quantity = input("Enter Quantity: ")
price = input("Enter Price: ")
dateTime = input("Enter date & time: ")
patientName = input("Enter Patient Name: ")

file = open("pharmacyReportDetails.txt", "w")
file.write(medid)
file.write("\n")
file.write(nameofmed)
file.write("\n")
file.write(quantity)
file.write("\n")
file.write(price)
file.write("\n")
file.write(dateTime)
file.write("\n")
file.write(patientName)
file.close()
